  apiVersion: v1
  kind: Service
  metadata:
    name: item-service
    labels:
      app: item-service
      app.kubernetes.io/component: item-service
      app.kubernetes.io/instance: item-service
      app.kubernetes.io/part-of: Services
      app.openshift.io/runtime-version: latest
  spec:
    selector:
      app: item-service
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 9080-tcp
      protocol: TCP
      port: 9080
      targetPort: 9080