version: '3'
services:
  user-db:
    image: registry.redhat.io/rhel8/postgresql-12
    container_name: user-container
    ports:
      - 9001:5432/tcp
    environment:
      POSTGRESQL_DATABASE: db
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_USER: user
  item-db:
    image: registry.redhat.io/rhel8/postgresql-12
    container_name: item-container
    ports:
      - 9002:5432/tcp
    environment:
      POSTGRESQL_DATABASE: db
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_USER: user
  purchase-db:
    image: registry.redhat.io/rhel8/postgresql-12
    container_name: purchase-container
    ports:
      - 9003:5432/tcp
    environment:
      POSTGRESQL_DATABASE: db
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_USER: user
  inventory-db:
    image: registry.redhat.io/rhel8/postgresql-12
    container_name: inventory-container
    ports:
      - 9004:5432/tcp
    environment:
      POSTGRESQL_DATABASE: db
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_USER: user