  apiVersion: v1
  kind: Service
  metadata:
    name: user-service
    labels:
      app: user-service
      app.kubernetes.io/component: user-service
      app.kubernetes.io/instance: user-service
      app.kubernetes.io/part-of: Services
      app.openshift.io/runtime-version: latest
  spec:
    selector:
      app: user-service
    ports:
    - name: tcp-http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: tcp-health
      protocol: TCP
      port: 9080
      targetPort: 9080