  apiVersion: v1
  kind: Service
  metadata:
    name: item-database
    annotations:
      template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  spec:
    selector:
      name: item-database
    ports:
    - name: item-database
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432