apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory-service
spec:
  hosts:
    - "*"
  gateways:
    - mesh-example-gateway
  http:
    - match:
        - uri:
            prefix: /api/inventory
      route:
        - destination:
            host: inventory-service
            port:
              number: 8080