apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: purchase-service
spec:
  hosts:
    - "*"
  gateways:
    - mesh-example-gateway
  http:
    - match:
        - uri:
            prefix: /api/purchase
      route:
        - destination:
            host: purchase-service
            port:
              number: 8080