  apiVersion: v1
  kind: Service
  metadata:
    name: user-database
    annotations:
      template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  spec:
    selector:
      name: user-database
    ports:
    - name: user-database
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432